=== EminentStar/tobi-spring/vol1/sqlmap.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.epril.com/sqlmap"
  xmlns:tns="http://www.epril.com/sqlmap" elementFormDefault="qualified">

  <element name="sqlmap">
    <complexType>
      <sequence>
        <element name="sql" maxOccurs="unbounded" type="tns:sqlType"/>
      </sequence>
    </complexType>
  </element>

  <complexType name="sqlType"> <!-- <sql>에 대한 정의를 시작 -->
    <simpleContent>
      <extension base="string"> <!-- sql 문장을 넣을 스틀이 타입을 정의함 -->
        <attribute name="key" use="required" type="string"/> <!-- 검색을 위한 키 값은 <sql>의 key 애트리뷰트에 넣음. 반드시 입력해야 하는 필수 값. -->
      </extension>
    </simpleContent>
  </complexType>

</schema>

=== EminentStar/tobi-spring/src/springbook/user/dao/sqlmap.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sqlmap xmlns="http://www.epril.com/sqlmap"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema"
  xsi:schemaLocation="http://www.epril.com/sqlmap/sqlmap.xsd">
  <sql key="userAdd">INSERT INTO users(id, name, password,
      level, login, recommend, email) VALUES(?,?,?,?,?,?,?)</sql>
  <sql key="userGet">SELECT * FROM users WHERE id = ?</sql>
  <sql key="userGetAll">SELECT * FROM users ORDER BY id</sql>
  <sql key="userGetCount">SELECT COUNT(*) FROM users</sql>
  <sql key="userUpdate">UPDATE users SET name = ?, password = ?, level = ?, login = ?, recommend = ?, email = ? where id = ?</sql>
  <sql key="userDelete">DELETE FROM users WHERE id = ?</sql>
  <sql key="userDeleteAll">DELETE FROM users</sql>
</sqlmap>
